export const S = {
  appName:  '🍅 蘇打石器 GM',
  appSub:   '私服後台管理系統',

  // Nav groups（與 EXE 一致）
  grpPlayer:   '玩家帳號',
  grpRecord:   '紀錄查詢',
  grpVip:      'VIP 系統',
  grpMonitor:  '玩家監控',
  grpGm:       'GM 功能',
  grpAnalysis: '數據分析',
  grpSystem:   '系統管理',

  navDashboard:   '統計面板',
  navPlayers:     '玩家管理',
  navMaster:      '主帳號查詢',
  navRecharge:    '充值記錄',
  navTradeLog:    '交易記錄',
  navGoldLog:     '金幣日誌',
  navMail:        '郵件記錄',
  navVip:         'VIP 玩家管理',
  navOnline:      '線上玩家',
  navBan:         '封號管理',
  navPetCmd:      'GM 寵物指令',
  navBatch:       '批量發送',
  navRecycle:     '角色回收桶',
  navItemQueue:   '道具給予',
  navBatchGold:   '批量金幣',
  navSql:         'SQL 查詢',
  navShop:        '商城分析',
  navPlayerAna:   '玩家活躍分析',
  navRechargeAna: '儲值趨勢分析',
  navTradeAudit:  '交易稽核',
  navGmLog:       'GM 操作日誌',
  navGmPerm:      'GM 權限管理',
  navBackup:      '備份還原',
  navGmAdmin:     '工具帳號',
  navLogout:      '登出',

  // Login
  loginTitle:   '🍅 蘇打石器 GM',
  loginSub:     '私服後台管理系統',
  loginUser:    '帳號',
  loginPass:    '密碼',
  loginBtn:     '登入',
  loginLoading: '登入中…',
  loginErr:     '帳號或密碼錯誤',
  loginPlhUser: 'GM 帳號',
  loginPlhPass: '密碼',

  // Dashboard
  statTotal:    '總玩家數',
  statOnline:   '目前在線',
  statBanned:   '已封號',
  statNewToday: '今日新增',
  statGold:     '全服金幣',
  statCrystal:  '全服水晶',
  shortcuts:    '快速入口',
  apiError:     'API 連線失敗，請確認 API 已啟動',
  apiErrorServer:'伺服器錯誤，請稍後再試',

  // Players
  pagePlayerMgr: '玩家管理',
  searchPlh:     '輸入帳號或角色名稱…',
  searching:     '搜尋中…',
  searchBtn:     '搜尋',
  searchHint:    '輸入關鍵字搜尋玩家',
  tagOnline:     '在線',
  tagBanned:     '封號',
  tagMuted:      '禁言',
  gold:          '金幣',
  crystal:       '水晶',
  regIP:         '註冊 IP',
  lastIP:        '最後 IP',
  regTime:       '註冊時間',
  loginTime:     '登入時間',
  unreadMail:    '未讀郵件',
  petCount:      '寵物數',
  setGold:       '設定',
  setCrystal:    '設定',
  updGold:       '✓ 金幣已更新',
  updCrystal:    '✓ 水晶已更新',
  banBtn:        '封號',
  unbanBtn:      '解除封號',
  banned:        '✓ 已封號',
  unbanned:      '✓ 已解封',
  banDays:       '封號天數（0=永久）',
  confirm:       '確認',
  cancel:        '取消',
  payTotal:      '累積儲值',
  rechargeBtn:   '充值',
  rechargeTitle: '給予儲值',
  rechargeTwd:   '台幣 (NT$)',
  rechargeGold:  '金幣',
  rechargeGiveGold: '同時發放金幣',
  rechargeConfirm: '確認給予儲值',
  rechargeDone:  '✓ 已給予儲值',

  // Online
  pageOnline:   '線上玩家',
  onlineCount:  (n: number) => `共 ${n} 人在線`,
  refresh:      '重整',
  colChar:      '角色名稱',
  colAccount:   '帳號',
  colChannel:   '頻道',
  colGold:      '金幣',
  colIP:        'IP',
  loading:      '載入中…',
  noOnline:     '目前沒有玩家在線',

  // Ban
  pageBan:      '封號管理',
  banAccount:   '帳號',
  banEndTime:   '到期時間',
  banPermanent: '永久',
  banAll:       '全部封號資料',
  unbanAll:     '全部解封',
  noBanned:     '目前沒有封號玩家',

  // Recharge (record + give)
  pageRecharge: '充值記錄',
  rechargeOnlyProgress: '僅更新累儲進度（不發金幣）',
  colAmount:    '金額',
  colTime:      '時間',
  colType:      '類型',
  noData:       '沒有資料',

  // Gold Log
  pageGoldLog:  '金幣日誌',
  colBefore:    '變更前',
  colAfter:     '變更後',
  colDiff:      '變動量',
  colOp:        '操作',

  // Batch
  pageBatch:    '批量發送',
  batchTarget:  '發送對象',
  batchAll:     '全部玩家',
  batchOnline:  '線上玩家',
  batchCustom:  '自訂義清單',
  batchTitle:   '標題',
  batchContent: '內容',
  batchSend:    '發送',
  batchSending: '發送中…',
  batchDone:    (n: number) => `✓ 已發送 ${n} 人`,

  // Pet cmd
  pagePetCmd:    'GM 寵物指令',
  petTarget:     '指定玩家（CDKEY）',
  petTargetPlh:  '帳號或角色名稱',
  petQuery:      '查詢',
  petFound:      (name: string, acc: string) => `✓ ${name}（${acc}）`,
  petIdLabel:    '寵物編號',
  petMkTitle:    '[gm petmake] 簡易給予',
  petLevel:      '等級',
  petRebirth:    '轉數',
  petCdkey:      '指定玩家 CDKEY（可選）',
  petCdkeyPlh:   '玩家登入帳號',
  petAbiTitle:   '[gm petmakeabi] 完整四維指定',
  petHp:         '血量(HP)',
  petAtk:        '攻擊',
  petDef:        '防突',
  petSpd:        '速度',
  petAbiNote:    '※ petmakeabi 只能生成給自己（無 CDKEY）',
  copy:          '複製',
  copied:        '✓ 已複製',
  minus:         '−',
  plus:          '+',
  em:            '—',
  oneK:          '千',
  tenK:          '萬',
}
